name: copiainsta
description: "Mini Instagram (Supabase + Flutter)"
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  image_picker: ^1.1.2
  uuid: ^4.4.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
